### ISSUE TITLE
Add intro

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#10]
![image](https://user-images.githubusercontent.com/28354997/95041751-9ab73300-06a5-11eb-8611-20f18f3e3d00.png)

- [ ] Remove bullet points
- [ ] Add an intro to hook learner. Example: At this stage you probably have a decent understanding of why GitHub is important and are able to use words like repositories in sentences at will. But you likely don't understand how developers take an issue and take it to a solution. In this lesson we will dig into the Developer Workflow

**Comment by chrisbean** [comment]
Did this in [commit 37c6d639194e814fabe16a0c5d55ca3225e7d0a0](https://github.com/chrisbean/Mastering_GitHub/commit/37c6d639194e814fabe16a0c5d55ca3225e7d0a0#diff-25d902c24283ab8cfbac54dfa101ad31). 

@kacres You may need to pull the latest?

**Comment by kacres** [comment]
Got the latest version but made the comment before doing a pull. I like the M1L3 intro 👍
