### ISSUE TITLE
Change Key terms into an assessment

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#11]
![image](https://user-images.githubusercontent.com/28354997/95042628-832d7980-06a8-11eb-8a74-9ec81a1b7099.png)

Instead of using the accordion  feature to show participants the definitions, let's make them figure it out themselves.

- [ ] remove the accordion

- [ ] The [Drag & Drop](https://danielstorey.github.io/adapt-demo-course/#/id/co-main) feature from Daniel Story would be a neat addition if possible

- [x] If Drag & Drop doesn't work, the core [Matching](https://adaptlearning.github.io/v4demo/#/id/co-10) plug-in could work fine as well.

**Comment by chrisbean** [comment]
Drag and drop isn't working; the functionality is fine, but there is no "submit" button, even when I run the example file. 

I've attempted using the older version "[draganddrop](https://github.com/danielstorey/adapt-draganddrop)" as well as the newer "[dragndrop](https://github.com/danielstorey/adapt-dragndrop)" with no result. 

Both of those repos were last updated in 2017, so may just not work with the current version of Adapt.
<img width="940" alt="Screen Shot 2020-10-05 at 12 52 24 PM" src="https://user-images.githubusercontent.com/3696499/95125463-e0a5e280-0709-11eb-8ef3-837bf202cec6.png">

**Comment by chrisbean** [comment]
Updated to matching activity

**Comment by chrisbean** [comment]
Updated.
