### ISSUE TITLE
Update: Why should you care? - GitHub helps developers...

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#2]
<img src="https://user-images.githubusercontent.com/28354997/95028105-d8976580-066b-11eb-991c-bb135f609485.png" width="200" height="200">

Looking at the text in the flippers, I think that some of it can be shortened and made a little more concise so that it reads better. I also like having a 'story' or scenario with each box to further engage the learner.

**Correct Problems**
- [x] Replace text: (flip 1) A bug is introduced into our codebase that causes customer checkouts to fail.

**Collaborate**
I think the changes below gets at the idea of collaboration better than the current text.
- [x] Replace text: (flip 1) The best products come from a mix of ideas, experiences, and perspectives. GitHub enables developers to share ideas and work together.
- [x] Replace text: (flip 2) When developers open a pull request it notifies others that their fix or feature is ready, and their code can be reviewed and discussed.

**Gain Context**
- [x] Replace text: (flip 1) Git lets developers see the entire history of the changes, decisions, and progression of a project.
- [x] Replace text: (flip 2) From the moment they access the history of a project, the developer has all the context they need to understand and start contributing

**Contain**
- [x] Replace text: (flip 1) Our code has to be stored in a place that is secure and accessible to all Shopifolk.
- [x] Replace text: (flip 2) Not only does GitHub provide a secure and reliable hosting service, it comes with many additional features to keep us moving fast.

**Comment by chrisbean** [comment]
Done! Really like these updates.
