### ISSUE TITLE
Replace graphic and hot graphic component - Git vs GitHub

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#6]
<img src="https://user-images.githubusercontent.com/28354997/95037336-a6e8c380-0698-11eb-9b36-7cd77c108d60.png" width="200" height="200">

**Thoughts**

- this is an attractive image but it is unclear. 
- I also don’t think that the hot graphic works here. The pins are too hard to see
- I think this image with a table or accordion might be better
- Here is a better picture of [Git vs GitHub] (https://www.simplilearn.com/ice9/free_resources_article_thumb/git_vs_github2.jpg) 
![image](https://user-images.githubusercontent.com/28354997/95037474-2b3b4680-0699-11eb-8fc8-9bba999991a6.png)

- Using this text provides a clearer comparison between the two:
![image](https://user-images.githubusercontent.com/28354997/95037499-44dc8e00-0699-11eb-9cbf-9a1264f2ca51.png)

**Comment by kacres** [comment]
Christine suggested using [Dan Storey's blinds or flipper](https://www.google.com/url?q=https://danielstorey.github.io/adapt-demo-course/%23/id/co-main&sa=D&ust=1601854363616000&usg=AFQjCNHioBcGhs_0GysGLtYA4_RyJS1xMA).

**Comment by kacres** [comment]
Either of these components would be great. My first inclination is to use the blinds.

**Comment by kacres** [comment]
This section is greatly improved. A couple of additional questions:
1. Is it possible to display the comparisons between the Git and GitHub simultaneously? 
For example: Git is software and GitHub is a service appear at the same time.
This would make it easier for the learner to compare and contrast between the two.

2. Is it possible to update the box around the text or eliminate it completely? The box looks a bit clunky over top of the image. 
![image](https://user-images.githubusercontent.com/28354997/95114845-907f4e00-0712-11eb-9db5-f3f05173f341.png)

**Comment by chrisbean** [comment]
Replaced with [stacklist](https://github.com/danielstorey/adapt-stacklist) from Daniel Storey.

Starting state: 
<img width="834" alt="Screen Shot 2020-10-05 at 3 06 35 PM" src="https://user-images.githubusercontent.com/3696499/95137348-b578be80-071c-11eb-949d-76121f193757.png">

Final state:
<img width="792" alt="Screen Shot 2020-10-05 at 3 01 56 PM" src="https://user-images.githubusercontent.com/3696499/95137368-bf9abd00-071c-11eb-8064-6f5dac2f850a.png">

**Comment by kacres** [comment]
This has become a great component. One last point. Would it be possible to make all the boxes align? This would require that the text in each of the boxes occupies the same number of lines. I think that this would create a cleaner look.

**Comment by chrisbean** [comment]
Done! (I think the forcing factor of tightening up length benefitted the clarity of language.)

<img width="822" alt="Screen Shot 2020-10-06 at 11 33 57 AM" src="https://user-images.githubusercontent.com/3696499/95245724-5d979180-07c8-11eb-86b9-2e3fe5e5200c.png">
