### ISSUE TITLE
Add final assessment

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#7]
The lesson needs a final assessment to bring everything together. While I am not a huge fan of multiple choice questions, they may be best suited to this module. Here are a few questions that could be added.

1. Git is (check all that apply) 
- A version control system
- A hosting service
- Run locally from a computer
- The same as GitHub

2. A new feature that is created would most likely follow which of the following workflows?
- issue > build feature > branch > code review > pull request > merge
- issue > branch > build feature > pull request > code review > merge
- build feature > branch > code review > deploy > pull request
- issue > pull request > branch > build feature > code review > merge

3. Which of the following are reasons that github is useful to developers and all Shopifolk (check all that apply)
- GitHub provides a history of all the changes that have occurred to our codebase
- GitHub allows developers to collaborate closely to share ideas and code
- GitHub can be used as both a project and task management tool
- GitHub is a command line tool that doesn't have a graphical interface

**Comment by chrisbean** [comment]
Added.
