### ISSUE TITLE
Title slide - Setting up your GitHub Account

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#8]
![image](https://user-images.githubusercontent.com/28354997/95040966-562a9800-06a3-11eb-9cc3-74de10a9a4a8.png)

- [ ] Remove bullet points and add a hook as an introduction. Sample: Now that you know a little about GitHub you can likely barely contain your excitement about getting a GitHub account and GitHub username and diving into some repositories! The wait is almost over. 
- Feel free to make something that sounds better :)

**Comment by chrisbean** [comment]
Intro currently reads: "So you need to create a GitHub account. Learn how to keep our code safe, find what you need, and make sure other Shopifolk can find you."

I like the voice you're using, happy to incorporate some of that!
