### ISSUE TITLE
Add final assessment

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#9]
For this lesson, a simple final assessment could be adding a link to your Vault profile that would show your GitHub username.

- [x] Add the [Text Input](https://github.com/adaptlearning/adapt-contrib-textInput/wiki) core component
- [x] Add the following prompt to the component: To finalize this lesson, paste a link to your profile in The Vault showing that you have added your GitHub username.

**Comment by chrisbean** [comment]
Added. 

I spent a while trying to get Adapt to accept a regex that would perceive _any_ input at all as "correct," but the quickest solution was to just provide positive "thank you!" feedback for "wrong" answers.
